<?php

namespace ContainerGPip837;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ax467XHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ax467XH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ax467XH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'serializerInterface' => '?',
        ]);
    }
}
