<?php

namespace ContainerGPip837;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnityOfWorkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'unity_of_work' shared autowired service.
     *
     * @return \App\Core\Domain\UnityOfWork\UnityOfWork
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Abstraction'.\DIRECTORY_SEPARATOR.'Interface'.\DIRECTORY_SEPARATOR.'IUnityOfWork.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'UnityOfWork'.\DIRECTORY_SEPARATOR.'UnityOfWork.php';

        return $container->services['unity_of_work'] = new \App\Core\Domain\UnityOfWork\UnityOfWork(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
