controllers:
    resource: ../src/Controller/
    type: annotation
    prefix:   '/api'
    trailing_slash_on_root: false

kernel:
    resource: ../src/Kernel.php
    type: annotation

api:
    prefix: /api
    resource: './routes/api-routes.yml'

login_check:
    path:     /login_check
    methods:  [POST]
