controllers:
    resource: ../src/Controller/
    type: annotation
    prefix:   '/api'
    trailing_slash_on_root: false

kernel:
    resource: ../src/Kernel.php
    type: annotation


# api:
#     prefix: /api

register:
    path: /register
    controller: App\Controller\UsuarioController::register

login:
    path:     /login
    methods:  [POST]
    controller: App\Controller\LoginController::login

login_check:
    path:     /login_check
    methods:  [POST]

test_protection:
    path: /test
    controller: App\Controller\UsuarioController::testProtection
