services:

    domain_notification_container:
        class: App\Core\Shared\Event\DomainNotificationContainer
        public: true
        tags: ['handler']
        shared: true

    generic_handler:
        class: App\Core\Shared\Handler\GenericHandler
        public: true
        tags: ['handler']

    user_service:
        class: App\Core\Domain\Service\UserService
        public: true


    App\Core\Shared\Handler\HandlerAggregator: '@handler_aggregator'
    App\Core\Shared\Event\DomainNotificationContainer: '@domain_notification_container'
    App\Core\Domain\Abstraction\Interface\IUserService: @user_service
    Symfony\Component\Cache\Adapter\AdapterInterface: '@cache.app'

        