services:
    handler_aggregator:
        class: App\Core\Shared\Handler\HandlerAggregator
        public: true
        tags: ['handler_aggregator']
        shared: true
        arguments:
            - { param1: '@domain_notification_container', param2: '@generic_handler' }

    domain_notification_container:
        class: App\Core\Shared\Event\DomainNotificationContainer
        public: true
        tags: ['handler']
        shared: true

    generic_handler:
        class: App\Core\Shared\Handler\GenericHandler
        public: true
        tags: ['handler']

    App\Core\Shared\Handler\HandlerAggregator: '@handler_aggregator'
    App\Core\Shared\Event\DomainNotificationContainer: '@domain_notification_container'
    Symfony\Component\Cache\Adapter\AdapterInterface: '@cache.app'

        