<?php

namespace ContainerQ0pVKpA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainNotificationContainerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'domain_notification_container' shared service.
     *
     * @return \App\Core\Shared\Event\DomainNotificationContainer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Abstraction'.\DIRECTORY_SEPARATOR.'Interface'.\DIRECTORY_SEPARATOR.'IDomainNotificationContainer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Abstraction'.\DIRECTORY_SEPARATOR.'Interface'.\DIRECTORY_SEPARATOR.'IHandler.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Event'.\DIRECTORY_SEPARATOR.'DomainNotificationContainer.php';

        return $container->services['domain_notification_container'] = new \App\Core\Shared\Event\DomainNotificationContainer();
    }
}
