<?php

namespace ContainerQ0pVKpA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioAppServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Core\Application\Service\UsuarioAppService' shared autowired service.
     *
     * @return \App\Core\Application\Service\UsuarioAppService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Abstraction'.\DIRECTORY_SEPARATOR.'Interface'.\DIRECTORY_SEPARATOR.'IUsuarioAppService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UsuarioAppService.php';

        return $container->services['App\\Core\\Application\\Service\\UsuarioAppService'] = new \App\Core\Application\Service\UsuarioAppService(($container->services['App\\Core\\Domain\\Service\\UsuarioService'] ?? $container->load('getUsuarioServiceService')));
    }
}
