<?php

namespace ContainerQ0pVKpA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Core\Domain\Service\UsuarioService' shared autowired service.
     *
     * @return \App\Core\Domain\Service\UsuarioService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Abstraction'.\DIRECTORY_SEPARATOR.'Interface'.\DIRECTORY_SEPARATOR.'IUsuarioService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Domain'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UsuarioService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'password-hasher'.\DIRECTORY_SEPARATOR.'Hasher'.\DIRECTORY_SEPARATOR.'UserPasswordHasherInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'password-hasher'.\DIRECTORY_SEPARATOR.'Hasher'.\DIRECTORY_SEPARATOR.'UserPasswordHasher.php';

        return $container->services['App\\Core\\Domain\\Service\\UsuarioService'] = new \App\Core\Domain\Service\UsuarioService(($container->services['App\\Core\\Domain\\Repository\\UsuarioRepository'] ?? $container->load('getUsuarioRepositoryService')), new \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher(($container->privates['security.password_hasher_factory'] ?? $container->load('getSecurity_PasswordHasherFactoryService'))), ($container->services['unity_of_work'] ?? $container->load('getUnityOfWorkService')));
    }
}
