services:

  App\Core\Domain\Service\:
    resource: '../../src/Core/Domain/Service/'
    public: true
    autowire: true

  App\Core\Domain\Repository\:
    resource: '../../src/Core/Domain/Repository/'
    public: true
    autowire: true

  unity_of_work:
          class: App\Core\Domain\UnityOfWork\UnityOfWork
          public: true
          autowire: true

  App\Core\Domain\Abstraction\Interface\IClienteRepository: '@App\Core\Domain\Repository\ClienteRepository'
  App\Core\Domain\Abstraction\Interface\IUsuarioRepository: '@App\Core\Domain\Repository\UsuarioRepository'
  App\Core\Domain\Abstraction\Interface\IProdutoRepository: '@App\Core\Domain\Repository\ProdutoRepository'
  App\Core\Domain\Abstraction\Interface\IPedidoRepository: '@App\Core\Domain\Repository\PedidoRepository'
  App\Core\Domain\Abstraction\Interface\IImagemRepository: '@App\Core\Domain\Repository\ImagemRepository'
  App\Core\Domain\Abstraction\Interface\IUsuarioService: '@App\Core\Domain\Service\UsuarioService'
  App\Core\Domain\Abstraction\Interface\IClienteService: '@App\Core\Domain\Service\ClienteService'
  App\Core\Domain\Abstraction\Interface\IProdutoService: '@App\Core\Domain\Service\ProdutoService'
  App\Core\Domain\Abstraction\Interface\IPedidoService: '@App\Core\Domain\Service\PedidoService'
  App\Core\Domain\Abstraction\Interface\IImagemService: '@App\Core\Domain\Service\ImagemService'
  App\Core\Domain\Abstraction\Interface\IFichaProducaoService: '@App\Core\Domain\Service\FichaProducaoService'
  App\Core\Domain\Abstraction\Interface\IClienteImagemService: '@App\Core\Domain\Service\ClienteImagemService'
  App\Core\Domain\Abstraction\Interface\IProdutoImagemService: '@App\Core\Domain\Service\ProdutoImagemService'
  App\Core\Domain\Abstraction\Interface\IClienteImagemRepository: '@App\Core\Domain\Repository\ClienteImagemRepository'
  App\Core\Domain\Abstraction\Interface\IProdutoImagemRepository: '@App\Core\Domain\Repository\ProdutoImagemRepository'
  App\Core\Domain\Abstraction\Interface\IUnityOfWork: '@unity_of_work'
  Symfony\Component\Cache\Adapter\AdapterInterface: '@cache.app'
