services:
    domain_notification_container:
        class: App\Core\Shared\Event\DomainNotificationContainer
        public: true
        tags: ['handler']
        shared: true

    generic_handler:
        class: App\Core\Shared\Handler\GenericHandler
        public: true
        tags: ['handler']

    auto_mapper_init:
        class:  App\Core\Shared\Mapper\AutoMapperInitializer
        public: true
        autowire: true

    paginated_request_handler:
        class: App\Core\Shared\Handler\PaginatedRequestHandler
        public: true
        autowire: true

    domain_notify_subscriber:
      class: App\Core\Shared\EventListener\DomainEventListener
      tags:
          - { name: domaineventlistener }   

    on_request_domain_notification_subscriber:
        class: App\Core\Shared\EventSubscribers\DomainNotificationSubscriber
        tags:
            - {  name: kernel.event_subscriber }
        autowire: true  

    on_request_response_subscriber:
        class: App\Core\Shared\EventSubscribers\ResponseDataSubscriber
        tags:
            - {  name: kernel.event_subscriber }
        autowire: true    

    on_request_paginated_request_handler_listener:
        class:  App\Core\Shared\EventSubscribers\PaginatedRequestHandlerListener
        tags:
            - {  name: kernel.event_subscriber }
        autowire: true  

    app.serializer:
        alias: Symfony\Component\Serializer\SerializerInterface
        public: true

    app.core.domain.provider.auth_user_provider:
        class: App\Core\Domain\Provider\AuthUserProvider
        arguments:
            - '@App\Core\Domain\Abstraction\Interface\IUsuarioRepository'
        public: true
        
    App\Core\Shared\Handler\HandlerAggregator: '@handler_aggregator'
    App\Core\Shared\Event\DomainNotificationContainer: '@domain_notification_container'
    App\Core\Shared\Mapper\AutoMapperInitializer: '@auto_mapper_init'
    App\Core\Shared\Abstraction\Interface\IPaginatedRequestHandler: '@paginated_request_handler'