<?php

namespace ContainerZxVGt5G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandlerAggregatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'handler_aggregator' shared service.
     *
     * @return \App\Core\Shared\Handler\HandlerAggregator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'HandlerAggregator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'GenericHandler.php';

        return $container->services['handler_aggregator'] = new \App\Core\Shared\Handler\HandlerAggregator(['param1' => ($container->services['domain_notification_container'] ?? ($container->services['domain_notification_container'] = new \App\Core\Shared\Event\DomainNotificationContainer())), 'param2' => ($container->services['generic_handler'] ?? ($container->services['generic_handler'] = new \App\Core\Shared\Handler\GenericHandler()))]);
    }
}
