<?php

namespace ContainerOcLxCWZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenericHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'generic_handler' shared service.
     *
     * @return \App\Core\Shared\Handler\GenericHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'GenericHandler.php';

        return $container->services['generic_handler'] = new \App\Core\Shared\Handler\GenericHandler();
    }
}
