<?php

namespace ContainerJ3aijA4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomainNotifySubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'domain_notify_subscriber' shared autowired service.
     *
     * @return \App\Core\Shared\EventListener\DomainEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Core'.\DIRECTORY_SEPARATOR.'Shared'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'DomainEventListener.php';

        return $container->privates['domain_notify_subscriber'] = new \App\Core\Shared\EventListener\DomainEventListener(($container->services['domain_notification_container'] ?? ($container->services['domain_notification_container'] = new \App\Core\Shared\Event\DomainNotificationContainer())));
    }
}
