<?php

namespace ContainerVzWGlVd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_63PV7jNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.63PV7jN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.63PV7jN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'serializerInterface' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'encoder' => '?',
            'serializerInterface' => '?',
        ]);
    }
}
