<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPip837\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPip837/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGPip837.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGPip837\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGPip837\App_KernelDevDebugContainer([
    'container.build_hash' => 'GPip837',
    'container.build_id' => 'f7c53240',
    'container.build_time' => 1651032584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPip837');
