<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcSM6Bl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcSM6Bl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcSM6Bl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcSM6Bl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcSM6Bl\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcSM6Bl',
    'container.build_id' => '54c08757',
    'container.build_time' => 1650755778,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcSM6Bl');
