<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVzWGlVd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVzWGlVd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVzWGlVd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVzWGlVd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVzWGlVd\App_KernelDevDebugContainer([
    'container.build_hash' => 'VzWGlVd',
    'container.build_id' => '5dc73ffd',
    'container.build_time' => 1650889687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVzWGlVd');
