api_usuario_post:
    path: /usuario
    controller: App\Controller\UsuarioController::register
    methods:  [POST]

api_usuario_get:
    path: /usuario
    controller: App\Controller\UsuarioController::get
    methods:  [GET]

api_usuario_get_by_id:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::getById
    methods:  [GET]

api_usuario_patch:
    path: /usuario
    controller: App\Controller\UsuarioController::patch
    methods:  [PATCH]

api_usuario_put:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::put
    methods:  [PUT]

api_usuario_delete:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::delete
    methods:  [DELETE]