api_usuario:
    prefix: /usuario
    resource: './usuario.yml'



# Clientes

api_cliente:
    prefix: /cliente
    resource: './cliente.yml'


# Produtos

api_produto:
    prefix: /produto
    resource: './produto.yml'

# Pedidos

api_pedido:
    prefix: /pedido
    resource: './pedido.yml'

api_ficha_producao:
    prefix: /ficha_producao
    resource: './ficha_producao.yml'