# Pedidos

api_pedido_post:
    path: /
    controller: App\Controller\PedidoController::subscribe
    methods:  [POST]

api_pedido_get:
    path: /
    controller: App\Controller\PedidoController::get
    methods:  [GET]

api_pedido_get_by_id:
    path: /{id}
    controller: App\Controller\PedidoController::getById
    methods:  [GET]

api_pedido_patch:
    path: /
    controller: App\Controller\PedidoController::patch
    methods:  [PATCH]

api_pedido_put:
    path: /{id}
    controller: App\Controller\PedidoController::put
    methods:  [PUT]

api_pedido_delete:
    path: /{id}
    controller: App\Controller\PedidoController::delete
    methods:  [DELETE]