nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['*']
        # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        max_age: 3600
        allow_headers: ['*']
    paths:
        '^/':
           allow_origin: ['*']
           allow_headers: ['*']
           allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
           max_age: 3600

        '~/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            max_age: 3600
